### ISSUE TITLE
penalized maximim entropy

### ISSUE THREAD

**Issue by knaaptime** [pysal/tobler#100]
another method to consider: https://github.com/jvtcl/pmedmize

**Comment by jvtcl** [comment]
I'm still waiting on the go-ahead for an open source release of [pymedm](https://www.osti.gov/servlets/purl/1883844). To avoid duplicating efforts in the meantime, would it be possible to use the [R port](https://github.com/jvtcl/pmedmize) (via `rpy2`) or the [Julia port](https://github.com/jvtcl/pmedmjl) (via `pyjulia`)?

**Comment by knaaptime** [comment]
thanks for the update Joe; fingers crossed. And thanks for the pointers (and i didn't know there was a julia implementation!), though I'm not sure its worth writing cross-language wrappers just yet. In the event that folks desperately need pmedm before the python code is available, we'll point them to those packages

**Comment by knaaptime** [comment]
im closing as not planned, but feel free to give me a shout if you want to send something up @jvtcl
