### ISSUE TITLE
BUG: area_interpolate fails in geometry column not named "geometry"

### ISSUE THREAD

**Issue by martinfleis** [pysal/tobler#102]
There are 7 rows in `area_interpolate` expecting `"geometry"` column. Therefore if your active geometry is called differently and there's no other `"geometry"` columns it fails. If there is inactive `"geometry"` column then it will likely fail as well.

**Comment by knaaptime** [comment]
thanks for raising this. I can think of a few other places in the library this happens as well. I should get this resolved here in pretty short order
