### ISSUE TITLE
enhance readme

### ISSUE THREAD

**Issue by sjsrey** [pysal/tobler#11]
- [x] replace image
- [ ] links to notebooks/demos/docs
- [x] badges (travis/coverage/doi)

**Comment by knaaptime** [comment]
resolved by #33 

I think it would be a good idea to setup the user guide from the example notebooks similar to what we've done with geosnap

**Comment by knaaptime** [comment]
we should also include a suggested citation

**Comment by Suvid-Singhal** [comment]
Hi,
is  links to notebooks/demos/docs done? Can I do it if its not?

**Comment by sjsrey** [comment]
@Suvid-Singhal your contribution would be most welcomed.
