### ISSUE TITLE
Untitled notebook

### ISSUE THREAD

**Issue by jGaboardi** [pysal/tobler#122]
There is currently an [Untitled notebook](https://github.com/pysal/tobler/blob/master/notebooks/Untitled.ipynb) in the `master` branch. This should be removed, correct?

**Comment by knaaptime** [comment]
yeah i was gonna do that and #121 at the same time, unless you wanna drop it now :)

**Comment by jGaboardi** [comment]
> unless you wanna drop it now :)

LOL. Nah, I just saw that and thought to make a note of it!

**Comment by knaaptime** [comment]
duplicate of #94
