### ISSUE TITLE
Explanation for intensive variables area interpolation

### ISSUE THREAD

**Issue by iki77** [pysal/tobler#145]
The code explain it  like

For an intensive variable, the estimate at target polygon j is:
-  v_j = \sum_i v_i w_{i,j}
-  w_{i,j} = a_{i,j} / \sum_k a_{k,j}

And from what I understand is that:
- i = source
- j = target

What is k in \sum_k a_{k,j} and where does it come from?

**Comment by sjsrey** [comment]
k indexes all the source areas that contribute to target area j.
