### ISSUE TITLE
h3fy: FutureWarning: Currently, index_parts defaults to True, but in the future, it will default to False to be consistent with Pandas. 

### ISSUE THREAD

**Issue by johnziebro** [pysal/tobler#158]
Python 3.8
Tobler 0.8.2
pandas 1.4.1
geopandas  0.10.0

Calling h3fy produces the following FutureWarning:

/home/REDACT/Projects/REDACT/.venv/lib/python3.8/site-packages/tobler/util/util.py:151: FutureWarning: Currently, index_parts defaults to True, but in the future, it will default to False to be consistent with Pandas. Use `index_parts=True` to keep the current behavior and True/False to silence the warning.
  source = source.explode()

**Comment by martinfleis** [comment]
Thanks for the report! This has been very recently fixed in #155 and will be shipped in the next release.
