### ISSUE TITLE
rename default branch from `master` to `main`

### ISSUE THREAD

**Issue by jGaboardi** [pysal/tobler#168]
rename default branch from `master` to `main`

xref: https://github.com/pysal/libpysal/issues/517

**Comment by jGaboardi** [comment]
@knaaptime Now would be a nice time to revisit this.

**Comment by jGaboardi** [comment]
My permissions will need to be bumped up for that. Otherwise, you can follow [this guide](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch) and make sure to opt for updating open PRs.

**Comment by knaaptime** [comment]
i think i updated the branch, but also think steering committee members should have maintain privileges on all pysal pacakges. Quick scan of the repo settings shows thats a little more difficult than id expect

**Comment by jGaboardi** [comment]
Yeah, I def don't have the keys to do that...

**Comment by jGaboardi** [comment]
Seems to have stalled out for some reason, but is starting back up again.
