### ISSUE TITLE
0.9 was not actually released

### ISSUE THREAD

**Issue by martinfleis** [pysal/tobler#173]
There was an attempt to cut 0.9 some time ago https://github.com/pysal/tobler/releases/tag/v0.9.0 but failed https://github.com/pysal/tobler/actions/runs/1882692308. 

I suggest removing the tag 0.9, fixing the action and cutting 0.9 properly from the current main.

**Comment by martinfleis** [comment]
Though it is a bit hard to figure out what needs to be fixed without an actual log.

**Comment by knaaptime** [comment]
weird. and the logs are gone, so cant see what happened. It looks like some pieces succeeded because version 0.9 is on pypi and conda, so it seems the git release is the only thing that failed?

**Comment by martinfleis** [comment]
Could be the changelog creation, that was a bit flaky.
