### ISSUE TITLE
Very Inaccurate results with area interpolation

### ISSUE THREAD

**Issue by rarearth** [pysal/tobler#175]
I am getting very different results between using masked area interpolation and the standard are interpolation. I am attempting to interpolate population from census tracts to a uniform hex grid from h3. The total population of all census tracts is `census_gdf.population.sum()` 5275541. I would expect to get close to the true total population when summing my interpolated values. 

When I use the `masked_area_interpolate` I recreate this value exactly but when I use `area_interpolate` I get 16695676 which is off by a factor of 3 almost. Exploring the values using `results.explore("population")` doesn't seem to match the underlying distribution of `census_gdf.explore("population")`.

I have also set the pixel values for my tif mask to include all land use types so there is effectively no mask being applied to my data.

I have also tried projecting to a different crs by using `.to_crs(crs=3857)` on my source and target data frames but this had no effect other than silencing the warnings so I didn't include it below.

```
Python version       : 3.10.11
IPython version      : 8.14.0

tobler   : 0.0.0
geopandas: 0.13.2
rasterio : 1.3.7
```

```
import os
import requests

os.environ['USE_PYGEOS'] = '0'

import pandas as pd
import geopandas as gpd
from tobler.area_weighted import area_interpolate
from tobler.util import h3fy

params = {
    "get": "P3_001N",
    "for": "tract:*",
    "in": "state:17&county:031",
}
url = "https://api.census.gov/data/2020/dec/dhc"

r = requests.get(url, params=params).json()
columns, data = r[0], r[1:]

pop_df = pd.DataFrame(data, columns=columns)

pop_df["GEOID"] = pop_df["state"] + pop_df["county"] + pop_df["tract"]
pop_df["P3_001N"] = pop_df["P3_001N"].astype(int)
pop_df.rename(columns ={"P3_001N": "population"}, inplace=True)

census_gdf = gpd.read_file("../data/2020/tl_2020_17_tract")
census_gdf.to_crs(epsg=4326, inplace=True)

census_gdf = census_gdf.merge(
    pop_df, on="GEOID", how="inner"
)
census_gdf.population.fillna(0, inplace=True)

chi_hex = h3fy(census_gdf, resolution=8, buffer=True, clip=True)

results = area_interpolate(
    source_df=census_gdf, target_df=chi_hex, intensive_variables=["population"], allocate_total=False
)

results.population.sum(), census_gdf.population.sum()

```
> (16695676.888928173, 5275541)

```
from tobler.dasymetric import masked_area_interpolate

tif_fp = "../data/Land_cover_2020_30m_TIF/NA_NALCMS_landcover_2020_30m/data/NA_NALCMS_landcover_2020_30m.tif"

results2 = masked_area_interpolate(
    raster=tif_fp, 
    source_df=census_gdf, 
    target_df=chi_hex, 
    pixel_values=list(range(20)),
    extensive_variables=['population']
)

results2.population.sum(), census_gdf.population.sum()
```
> (5275541.002755635, 5275541)

census tracts found here https://www2.census.gov/geo/tiger/TIGER2020/TRACT/
land cover raster found here http://www.cec.org/north-american-environmental-atlas/land-cover-30m-2020/

**Comment by knaaptime** [comment]
in `results1` you're treating population as an intensive variable

**Comment by rarearth** [comment]
🤦 ugh thanks

**Comment by knaaptime** [comment]
happens :) Glad all we needed in this case was another set of eyes. Hope the package is working out for you otherwise
