### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by knaaptime** [pysal/tobler#178]
working on the meta release yesterday, @sjsrey and i realized some packages like spopt and momepy arleady have a release action that [generates a changelog](https://github.com/pysal/mapclassify/blob/main/.github/release.yml). I'm sure i was aware of that once, but have long since forgotten. Lets adopt that action in all the subpackages. If all the subpackages follow the same conventions we can build some simple tooling to creates the changelog for meta

**Comment by martinfleis** [comment]
Momepy doesn't. I'm still not sure how to implement it to have an up to date changelong in docs. That cannot be generated by the release action triggered by a tag.

**Comment by knaaptime** [comment]
ah, my mistake. The momepy changelog looks jsut like the one from spopt and mapclassify, so i figured it came from the same spot. The mapclassify one was autogenerated the other day https://github.com/pysal/mapclassify/releases/tag/v2.6.0 (to our surprise), so *something* is working. Looks like the recipe is dead simple and enumerates bug fixes, enhancements and [any unlabeled] PR along with the user who created the PR

i know we've discussed a few different options for automated changelogs, without ever finding a satisfactory option (e.g. listing all commits is too much), but for the metarelease, we want to create some tooling that captures changes from across the subpackages, so we were cooking up some tooling that grabs the changelog from each subpackage and cats them into a larger one for meta (but then that depends on a structured format for each of the subpkgs)

**Comment by martinfleis** [comment]
@jGaboardi I summon you! 

You probably know the situation best.

**Comment by jGaboardi** [comment]
xref https://github.com/pysal/esda/issues/250#event-9696173512
