### ISSUE TITLE
Site docs return 404

### ISSUE THREAD

**Issue by JosiahParry** [pysal/tobler#204]
The 3 vignettes at pysal.org/tobler presently return a 404 with nbviewer. 

For example: https://nbviewer.org/github/pysal/tobler/blob/master/notebooks/census_to_hexgrid.ipynb

**Comment by knaaptime** [comment]
hm, looks like thats cause they're still pointing at master instead of main (swap and it [works fine](https://nbviewer.org/github/pysal/tobler/blob/main/notebooks/census_to_hexgrid.ipynb))

im not actually sure where thats happening cause that notebook is sitting in the docs dir where it should be. Will take a look, thanks for raising

**Comment by knaaptime** [comment]
@jGaboardi do you remember where those are set?

**Comment by jGaboardi** [comment]
> https://nbviewer.org/github/pysal/tobler/blob/master/notebooks/census_to_hexgrid.ipynb

Where is that above link coming from? Are you simply launching nbviewer manually or do we have that link embedded somewhere in the repo/docs site?

**Comment by jbousquin** [comment]
Looks like those nbviewer links are hardcoded directly in the [index.rst](https://github.com/pysal/tobler/blob/main/docs/index.rst) (lines ~13, 21, 29, so just a link update?).

For the docs [tutorial page](https://pysal.org/tobler/tutorial.html),  [tutorial.rst](https://github.com/pysal/tobler/blob/main/docs/tutorial.rst) is pointing to the notebooks in docs/notebooks (e.g., [01_interpolation_methods_overview.ipynb](https://github.com/pysal/tobler/blob/main/docs/notebooks/01_interpolation_methods_overview.ipynb)). I ran into this recently in a different project where I didn't want to maintain two copies. sphinx may not like ../ and I found [nbsphinx_link](https://github.com/vidartf/nbsphinx-link) worked for me if you're open to the added docs requirement.

**Comment by jGaboardi** [comment]
> Looks like those nbviewer links are hardcoded directly in the [index.rst](https://github.com/pysal/tobler/blob/main/docs/index.rst) (lines ~13, 21, 29, so just a link update?).

Yep, this looks to be the case!

**Comment by knaaptime** [comment]
Sweet, thanks @jbousquin! Nbsphinx_link looks great

**Comment by knaaptime** [comment]
resolved by #219
