### ISSUE TITLE
cut new release of tobler?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/tobler#216]
Should we cut a new release of tobler after the current meta freeze?

**Comment by martinfleis** [comment]
https://github.com/pysal/tobler/pull/209 should've already been out ages ago. So yes, please do a patch asap.

**Comment by knaaptime** [comment]
Sure. I forgot that patch happpened; thought tobler was pretty up to date

**Comment by knaaptime** [comment]
i think there are some docs issues to work out, but i'd rather go ahead and get the release out then work on the docs separately. what do you think

**Comment by jGaboardi** [comment]
Agree. Let's try a with at least 1 release candidate though to make sure nothing else in the workflows are mucked up.

**Comment by jGaboardi** [comment]
[mucked up](https://github.com/pysal/tobler/actions/runs/10079409094)

**Comment by knaaptime** [comment]
its fixed. apparently i hadn't verified my email on pypi

**Comment by jGaboardi** [comment]
🥳

**Comment by jGaboardi** [comment]
Let's wait for the `conda-forge` release to close this out.

**Comment by jGaboardi** [comment]
@knaaptime Should [this draft version](https://github.com/pysal/tobler/releases/tag/untagged-22154e4534224c275618) be deleted?

**Comment by knaaptime** [comment]
yes. probably an artifact from the one I had to delete to re-release
