### ISSUE TITLE
handle remote rasters

### ISSUE THREAD

**Issue by knaaptime** [pysal/tobler#49]
ideally users should be able to stream the NLCD data without downloading all 3+gb. `rasterio` can read remote files from s3, but requires a context manager to get around AWS authentication

```python
with rasterio.env.Env(aws_unsigned=True):
	raster = rasterio.open(path)
```

we can use that scheme when we read files directly, but currently rasterstats is [unable](https://github.com/perrygeo/python-rasterstats/issues/208) to inherit that context. I'm opening this here so we can figure out how best to handle

**Comment by knaaptime** [comment]
it took me *forever* to figure out this error was coming from rasterstats instead of rasterio

**Comment by kannes** [comment]
As a user I would feel weird (and it might be a privacy issue) if requests were silently done to remote servers when I am doing my analysis. I would rather expect myself needing to supply the data in question. This would also allow people in other countries or with slightly different use-cases to use your tool.

**Comment by knaaptime** [comment]
hi, thanks for the feedback. The function i'm referencing here actually [takes](https://github.com/pysal/tobler/blob/f1dedf30a9e66739438faef5296c58a3666b3129/tobler/dasymetric/models.py#L20) a path to a raster, unless a user passes a 'convenience string' as a shorcut--and if a user wants to leverage one of those conveniences, we should be able to stream the data instead of them to download *all* of it. 

If a user wants to use data from another country, he or she can do so by supplying a path to the raster, in which case `tobler` makes no call to a remote server, silent or otherwise

**Comment by kannes** [comment]
That's awesome!

**Comment by knaaptime** [comment]
if the underlying issue is addressed upstream, we'll return to this
