### ISSUE TITLE
crs checking

### ISSUE THREAD

**Issue by knaaptime** [pysal/tobler#50]
we do some CRS checking to make sure that the rasters align properly with input vector data. Right now, those checks are pretty naive and issue a warning if there's a mismatch, but with the [new pyproj](https://github.com/geopandas/geopandas/pull/1292/files) now upstream in geopandas, we can be much more intelligent about these checks

**Comment by jGaboardi** [comment]
May we want to put that in some kind of utility embedded in libpysal so can use it across submodules? Could be useful in spaghetti.

**Comment by knaaptime** [comment]
I havent added anything fancy, but we were doing a length check before, since the crs used to be a dictionary.  The new crs is a class so that check causes breakage with new versions of geopandas. I've gone ahead and removed it, but we should do a hotfix release here, otherwise you cant use tobler's raster functions

**Comment by knaaptime** [comment]
this is now handled in geopandas
