### ISSUE TITLE
Consider usage of data.store_rasters() for examples

### ISSUE THREAD

**Issue by renanxcortes** [pysal/tobler#6]
Currently, some notebooks suggest downloading raster files similarly explained in https://github.com/locationtech-labs/geopyspark. However, since we have now the `data.store_rasters()` function, we can leverage the usage of the package showing how to use this function rather than the current approach.

**Comment by knaaptime** [comment]
we removed the `store_rasters` function to reduce the dependency footprint, but we should still document how users [who have quilt] can quickly download nlcd data from our bucket with

```python
import quilt3
p = quilt3.Package.browse("rasters/nlcd", "s3://spatial-ucr")
p["nlcd_2011.tif"].fetch()
```
