### ISSUE TITLE
jupyter example

### ISSUE THREAD

**Issue by dialuser** [pysal/tobler#72]
I tried to follow the examples in jupyter notebooks under \example. It seems many  of the imports do not work, for example,

 from tobler.vectorized_raster_interpolation import *
 from tobler import harmonize

**Comment by knaaptime** [comment]
hey, thank you for raising this. The API has had several changes over the past few months and the examples are woefully outdated. I'll try and get those updated quickly as i'm planning to get a new release of the package finished before July 1. In the meantime, [the docs](https://pysal.org/tobler/api.html) *are* up to date, so hopefully they can provide some small guidance in the interim

**Comment by dialuser** [comment]
Thank you. I really like your package.

**Comment by knaaptime** [comment]
resolved by #80 

see <https://github.com/pysal/tobler/blob/master/notebooks/interpolation_methods.ipynb>
