### ISSUE TITLE
Correct testing in unittests.yml?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/tobler#75]
In the [*Download Data* - *Pytest* steps of `unittests.yml`](https://github.com/pysal/tobler/blob/f5633c355afc500f4b6ee452ce2053e1083ec795/.github/workflows/unittests.yml#L56-L75) the testing seems to be exclusively pointing towards `geosnap`. Should this be testing `spatialucr/geosnap` or `pysal/tobler`?

**Comment by knaaptime** [comment]
good catch. i left a bunch of crap in there by accident in my haste to just get the workflow active but didnt finish building the tests last night. should be solved by #76 


the larger issue is that we're [hitting](https://github.com/knaaptime/tobler/runs/822744449?check_suite_focus=true) the [same issue](https://github.com/spatialucr/geosnap/issues/241) as geosnap where python 3.8 can resolve the package deps (which means its probably `tobler`'s fault, not `region`'s?).
