### ISSUE TITLE
Reorganize repository

### ISSUE THREAD

**Issue by sjsrey** [pysal/tobler#82]
The following directories have stale code  that is confusing to users:

- [ ] examples
- [ ] gists

We should move any functionality that is reflected in there into a feature branch in the tobler directory (or notebooks).

**Comment by knaaptime** [comment]
i think we can just remove them both. The notebooks there are mostly for dev use, demoing to the team how the internal methods work. The one or two others demo an outdated api, so i dont think there's actually much to salvage
